### ISSUE TITLE
Cardinal Issues

### ISSUE THREAD

**Issue by mitchts** [MCResourcePile/overcast-maps-a-to-f#7]
Maps that aren't listed here that are in this repository haven't been tested with Cardinal yet. 

**Acear II**
 - [ ] Broken void regions

**Araxa**
 - [ ] Wool room block filters broken

**Ascendance**
 - [ ] Objectives basically don't exist

**Brisked**
 - [ ] Redeemable scorebox doesn't work

**Build: Parkour**
 - [ ] Basically everything doesn't work

**Cat's Cradle**
 - [ ] Hills don't award points

**Ces**
 - [ ] Monuments don't register as being broken

**Coral Reef**
 - [ ] Can't break any blocks

**DynaboOo**
 - [ ] Wool room enter filters are broken

**Fracture**
 - [ ] Spawns don't work

**Wit's End**
 - [ ] Wool room enter filters are broken

**Block Runner maps**
 - [ ] FFA isn't supported
 - [ ] Structures aren't supported

**Ghost Squadron maps**
 - [ ] GS class modules aren't supported
 - [ ] FFA isn't supported

**Free-for-all and Micro maps**
 - [ ] FFA isn't supported

**Skywars maps**
 - [ ] FFA isn't supported
 - [ ] Lootables aren't supported

**Comment by Pablete1234** [comment]
Most of the region things broken are because cardinal doesn't use apply region priority, it was made way before that was a thing, and it isn't ready to support it.
The easiest fix is to change XMLs to expect ALL regions to apply (regardless of order, aka pre 1.3.3 proto behaviour), that basically means, allowing regions don't do anything, as the denying ones (even if placed after the allow one) will still apply.

**Comment by Pablete1234** [comment]
Fixes to some maps, or reasons why they can't be fixed:

#### Acear II
There's an "always" region that allows bridging between spawn and the map, but it's outside the "you may not edit blocks outside the map" region, so you can't build there.
Fix: make the "never" region the negative of the union between spawn bridges and the map, instead of only the negative of only the map

#### Araxa
Works fine for me

#### Ascendance
It was a bug with region stuff that changed in sport bukkit, fixed in cardinal now

#### Cat's Craddle
Replace "ratio" with "points"

#### Ces
Replace "material" with "materials"

#### Coral reef
Allowing stained clay is denying everything else

#### Dynaboo
There are 2 enter applies and 2 "modify" applies, that also filter enter, and they are mixed, so one filter allows you in one and denies you in the other one, and the other way arround

#### Fracture
Spawns don't allow a region to be specified via attribute, you'll have to put the spawn region in a child element,
Additional issues:

- Control point's "points" can't be 0.4 (must be round numbers),
- Structure module is a missing feature

#### Wit's End
Only-red/blue filters are made in a very wierd way, fix: `<team id="only-red">red</red>`

**Comment by Pablete1234** [comment]
Ces: replace "material" with "materials"

**Comment by Pablete1234** [comment]
Dynaboo: there are 2 enter applies and 2 "modify" applies, that also filter enter, and they are mixed, so one filter allows you in one and denies you in the other one, and the other way arround

**Comment by mitchts** [comment]
With the release of PGM fixing these maps to work on Cardinal probably isn't worth the effort.
